/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void appCanBeInstantiated() {
        // Verify that the App class can be instantiated
        assertNotNull("App class should not be null", App.class);
    }
}
